import { Inter, Montserrat, Playfair_Display } from "next/font/google";

import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider/theme-provider";
import ToastProvider from "@/components/ToastorProvider/ToasterProvider";

const inter = Inter({
  weight: ["300", "400", "500", "600", "700"],

  variable: "--font-inter",

  subsets: ["latin"],
});

export const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "700"],

  variable: "--font-montserrat",

  subsets: ["latin"],
});

export const playfair = Playfair_Display({
  weight: ["400", "500", "600", "700"],

  variable: "--font-playfair",

  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${montserrat.variable} ${playfair.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        suppressHydrationWarning
        className={`${inter.className} min-h-full flex flex-col`}
      >
        {/* এখানে মডিফাই করা হয়েছে */}

        <ThemeProvider
          attribute={["class", "data-theme"]}
          defaultTheme="system"
          enableSystem
          value={{
            light: "light",

            dark: "dark",
          }}
        >
          <ToastProvider>
            <main>{children}</main>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
